//! Host-side IO fanout generation (kata xa0f).
//!
//! The host step that auto-routes the IO (input/output) connections after a
//! routing pattern has produced its [`RoutingResult`] and **before** the
//! strict validator runs. It is pattern-agnostic: patterns stay
//! motor-focused and never emit IO themselves; the host appends
//! [`IoPad`]s / [`IoTrace`]s (the additive element families from
//! [`crate::io`]) for every coil terminal.
//!
//! # Placement strategy (default)
//!
//! A **connector row at the board edge**: every coil terminal fans out with
//! one straight, single-layer trace to its own connector pad on the nearest
//! across-travel board edge (`y = 0` or `y = board_width_mm`).
//!
//! - Pads of a row are evenly spaced along the travel axis, ordered to match
//!   their terminals' x order (a monotone terminal→pad assignment, so fanout
//!   traces within a row never cross each other).
//! - `IoFanoutOptions::tht` (the default sizing path) emits plated through
//!   -hole pads sitting one pad radius inboard of the edge so the drill stays
//!   on the board; `IoFanoutOptions::board_edge` emits castellated
//!   [`IoPadKind::BoardEdge`] pads centred exactly on the outline. An IC
//!   -footprint strategy (pads in the active area, `IoTraceRole::Tail` exits)
//!   remains possible through the schema but is not generated by this step.
//! - Each generated pad declares copper on the layer(s) that make the
//!   electrical connection real: all copper layers for THT (a through-hole
//!   pad spans the stack), exactly the fanout's layer for surface pads.
//!
//! # Nets, crossings, layers
//!
//! - Net assignment is pass-through: a pad/trace inherits the net (phase
//!   label) of the coil terminal it connects. A phase with several coil
//!   groups simply gets several same-net connector pads.
//! - Fanouts stay on a single layer (the terminal's layer); no vias are
//!   generated. The nearest-edge row makes every fanout a short straight
//!   trace on its own layer, so a layer change is never genuinely required.
//! - `IoTraceRole::Tail` is not used by the default strategy: the pads sit at
//!   the board-edge exit already, so there is no pad→edge tail to add.
//!
//! # Sizing authority
//!
//! The generator **reads** sizes from [`IoFanoutOptions`]; it never decides
//! them. The sizing authority is the DFM crate's `DesignRules`
//! (`pcbmotorgen-dfm`, downstream): the rules cannot be referenced from this
//! leaf crate, so callers bridge them in — see
//! `DesignRules::io_fanout_options()` for the canonical bridge
//! (`io_tht_pad_diameter_mm` + `min_via_drill_mm`).
//!
//! # Determinism
//!
//! The step is a pure function of `(result, ctx, options)`: same inputs,
//! byte-identical IO elements. Degenerate fanouts (a terminal exactly on its
//! pad slot) are avoided by construction with a deterministic in-bounds
//! nudge, because the strict validator rejects zero-length traces — the
//! generator must emit valid geometry, never nearly-invalid geometry.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::context::RoutingContext;
use crate::io::{IoPad, IoPadKind, IoTrace, IoTraceRole, PadSize};
use crate::model::{Layer, Net, Point, RoutingResult};

/// Fanout traces shorter than this are degenerate: the strict validator
/// rejects traces of length ≤ 1e-6 mm, so the generator keeps every fanout
/// comfortably above that bound and nudges pad slots that land on a terminal.
const MIN_FANOUT_LENGTH_MM: f64 = 1e-4;

/// Which across-travel board edge(s) host the connector row(s).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IoFanoutEdge {
    /// One row per used edge: each terminal fans out to the nearest
    /// across-travel edge (`y <= board_width/2` → `y = 0`, else
    /// `y = board_width`; the tie goes to `y = 0`). Keeps every fanout short.
    #[default]
    NearestAcrossEdge,
    /// All pads on the `y = 0` edge (single row).
    AcrossMin,
    /// All pads on the `y = board_width` edge (single row).
    AcrossMax,
}

/// Host options for [`generate_io_fanout`].
///
/// The generator reads sizes from here and never decides them — bridge the
/// values from the DFM `DesignRules` snapshot (see the [module docs](self)).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct IoFanoutOptions {
    /// Connector pad copper diameter, in mm (pads are generated circular).
    /// Bridge from `DesignRules::io_tht_pad_diameter_mm()` for THT pads.
    pub pad_diameter_mm: f64,
    /// Plated drill diameter, in mm. `Some` ⇒ [`IoPadKind::Tht`] pads placed
    /// one pad radius inboard of the edge (the drill must stay on the board);
    /// `None` ⇒ [`IoPadKind::BoardEdge`] castellated pads centred exactly on
    /// the outline.
    #[serde(default)]
    pub drill_mm: Option<f64>,
    /// Which across-travel edge(s) host the connector row(s).
    #[serde(default)]
    pub edge: IoFanoutEdge,
}

impl IoFanoutOptions {
    /// The default strategy: a THT connector row near the board edge. Size it
    /// from the DFM rules (`DesignRules::io_fanout_options()` does exactly
    /// that).
    pub fn tht(pad_diameter_mm: f64, drill_mm: f64) -> Self {
        Self {
            pad_diameter_mm,
            drill_mm: Some(drill_mm),
            edge: IoFanoutEdge::default(),
        }
    }

    /// Castellated board-edge row: surface copper centred on the outline,
    /// no drill.
    pub fn board_edge(pad_diameter_mm: f64) -> Self {
        Self {
            pad_diameter_mm,
            drill_mm: None,
            edge: IoFanoutEdge::default(),
        }
    }
}

/// One coil terminal to fan out: a position plus the (layer, net) of the coil
/// group it belongs to.
#[derive(Debug, Clone, PartialEq)]
struct Terminal {
    position: Point,
    layer: Layer,
    net: Net,
}

/// Generate the connector pads + fanout traces for every coil terminal of
/// `result`, appending them to `result.io_pads` / `result.io_traces`.
///
/// Runs host-side, after pattern generation and before validation; the
/// generated IO must pass the strict validator, so the geometry emitted here
/// is valid by construction (in-bounds, non-degenerate, rule-consistent pad
/// stacks). Errors are limited to impossible option values — geometric
/// corner cases are avoided by construction instead.
pub fn generate_io_fanout(
    result: &mut RoutingResult,
    ctx: &RoutingContext,
    opts: &IoFanoutOptions,
) -> Result<(), String> {
    if !opts.pad_diameter_mm.is_finite() || opts.pad_diameter_mm <= 0.0 {
        return Err(format!(
            "io fanout pad_diameter_mm = {} — pad sizes must be finite and positive",
            opts.pad_diameter_mm
        ));
    }
    if let Some(drill) = opts.drill_mm {
        if !drill.is_finite() || drill <= 0.0 {
            return Err(format!(
                "io fanout drill_mm = {drill} — drill diameters must be finite and positive"
            ));
        }
    }
    if !(ctx.active_area_length_mm.is_finite() && ctx.active_area_length_mm > 0.0) {
        return Err("io fanout needs a positive active_area_length_mm".to_string());
    }

    let terminals = collect_coil_terminals(result);
    if terminals.is_empty() {
        return Ok(());
    }

    let rows = assign_rows(&terminals, ctx, opts.edge);
    let mut pads: Vec<IoPad> = Vec::new();
    let mut traces: Vec<IoTrace> = Vec::new();

    for row in [Row::Min, Row::Max] {
        let mut row_terms: Vec<&Terminal> = terminals
            .iter()
            .zip(rows.iter())
            .filter_map(|(t, r)| (*r == row).then_some(t))
            .collect();
        // Deterministic row order: left-to-right along the travel axis, then
        // y / layer / net as tie-breakers. The monotone terminal→pad
        // assignment below keeps fanout traces within a row non-crossing.
        row_terms.sort_by(|a, b| {
            a.position
                .x
                .total_cmp(&b.position.x)
                .then(a.position.y.total_cmp(&b.position.y))
                .then(a.layer.cmp(&b.layer))
                .then(a.net.cmp(&b.net))
        });
        if row_terms.is_empty() {
            continue;
        }

        let pad_y = row_pad_y(row, ctx, opts);
        let xs = row_pad_xs(row_terms.len(), ctx, opts);
        for (k, term) in row_terms.iter().enumerate() {
            let mut pad_x = xs[k];
            let slot = Point::new(pad_x, pad_y);
            if term.position.distance_to(slot) <= MIN_FANOUT_LENGTH_MM {
                pad_x = nudge_in_bounds(pad_x, ctx.active_area_length_mm, opts.pad_diameter_mm);
            }
            let position = Point::new(pad_x, pad_y);
            if term.position.distance_to(position) <= MIN_FANOUT_LENGTH_MM {
                return Err(
                    "io fanout could not place a non-degenerate trace for a coil terminal"
                        .to_string(),
                );
            }

            let (kind, layers) = if opts.drill_mm.is_some() {
                (IoPadKind::Tht, (0..ctx.num_layers).collect::<Vec<Layer>>())
            } else {
                (IoPadKind::BoardEdge, vec![term.layer])
            };
            pads.push(IoPad {
                position,
                size: PadSize {
                    x: opts.pad_diameter_mm,
                    y: opts.pad_diameter_mm,
                },
                drill_mm: opts.drill_mm,
                layers,
                kind,
                net: term.net.clone(),
                number: Some((pads.len() + 1).to_string()),
            });
            traces.push(IoTrace {
                start: term.position,
                end: position,
                layer: term.layer,
                net: term.net.clone(),
                role: IoTraceRole::Fanout,
            });
        }
    }

    result.io_pads.extend(pads);
    result.io_traces.extend(traces);
    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Row {
    Min,
    Max,
}

/// Assign every terminal to its connector row.
fn assign_rows(terms: &[Terminal], ctx: &RoutingContext, edge: IoFanoutEdge) -> Vec<Row> {
    let half = ctx.board_width_mm / 2.0;
    terms
        .iter()
        .map(|t| match edge {
            IoFanoutEdge::AcrossMin => Row::Min,
            IoFanoutEdge::AcrossMax => Row::Max,
            IoFanoutEdge::NearestAcrossEdge => {
                if t.position.y <= half {
                    Row::Min
                } else {
                    Row::Max
                }
            }
        })
        .collect()
}

/// Pad centre y for a row: castellated pads sit exactly on the outline, THT
/// pads one pad radius inboard so the drill stays on the board (clamped into
/// the board width).
fn row_pad_y(row: Row, ctx: &RoutingContext, opts: &IoFanoutOptions) -> f64 {
    let inset = opts.pad_diameter_mm / 2.0;
    match (row, opts.drill_mm.is_some()) {
        (Row::Min, false) => 0.0,
        (Row::Max, false) => ctx.board_width_mm,
        (Row::Min, true) => inset.min(ctx.board_width_mm),
        (Row::Max, true) => (ctx.board_width_mm - inset).max(0.0),
    }
}

/// Evenly spaced pad centre x positions across the travel axis, one per
/// terminal of the row, keeping the end pads `margin` inboard (clamped so the
/// spacing never collapses).
fn row_pad_xs(n: usize, ctx: &RoutingContext, opts: &IoFanoutOptions) -> Vec<f64> {
    let l = ctx.active_area_length_mm;
    if n == 1 {
        return vec![l / 2.0];
    }
    let margin = opts.pad_diameter_mm.min(l / 3.0);
    let step = (l - 2.0 * margin) / (n - 1) as f64;
    (0..n).map(|k| margin + k as f64 * step).collect()
}

/// Deterministic in-bounds nudge for a pad slot that coincides with its
/// terminal: shift along the travel axis away from the nearer end.
fn nudge_in_bounds(x: f64, length: f64, diameter: f64) -> f64 {
    let nudge = diameter.min(length / 3.0);
    if x <= 2.0 * length / 3.0 {
        x + nudge
    } else {
        x - nudge
    }
}

/// Collect the electrical terminals of every coil group: elements grouped by
/// `(layer, net)` in emission order (segments, then curves — the same
/// grouping the `PhaseCoil` adapter uses); each group contributes its first
/// element's start and last element's end.
fn collect_coil_terminals(result: &RoutingResult) -> Vec<Terminal> {
    fn track(
        layer: u32,
        net: &str,
        start: Point,
        end: Point,
        order: &mut Vec<(u32, String)>,
        ends: &mut HashMap<(u32, String), (Point, Point)>,
    ) {
        let key = (layer, net.to_string());
        match ends.get_mut(&key) {
            None => {
                order.push(key.clone());
                ends.insert(key, (start, end));
            }
            Some(e) => e.1 = end,
        }
    }

    let mut order: Vec<(u32, String)> = Vec::new();
    let mut ends: HashMap<(u32, String), (Point, Point)> = HashMap::new();

    for s in &result.segments {
        track(s.layer, &s.net, s.start, s.end, &mut order, &mut ends);
    }
    for c in &result.curves {
        track(c.layer, &c.net, c.start, c.end, &mut order, &mut ends);
    }

    let mut terminals = Vec::new();
    for key in order {
        let (start, end) = ends[&key];
        terminals.push(Terminal {
            position: start,
            layer: key.0,
            net: key.1.clone(),
        });
        terminals.push(Terminal {
            position: end,
            layer: key.0,
            net: key.1,
        });
    }
    terminals
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::RouteSegment;

    fn ctx(length: f64, width: f64, layers: u32) -> RoutingContext {
        RoutingContext {
            active_area_length_mm: length,
            board_width_mm: width,
            num_layers: layers,
            phases: 3,
            min_trace_mm: 0.1,
            min_space_mm: 0.1,
            ..RoutingContext::default()
        }
    }

    fn seg(x1: f64, y1: f64, x2: f64, y2: f64, layer: u32, net: &str) -> RouteSegment {
        RouteSegment {
            start: Point::new(x1, y1),
            end: Point::new(x2, y2),
            layer,
            net: net.into(),
            is_active: true,
        }
    }

    fn tht_opts(d: f64) -> IoFanoutOptions {
        IoFanoutOptions::tht(d, 0.2)
    }

    #[test]
    fn invalid_options_are_rejected_and_result_untouched() {
        let mut r = RoutingResult {
            segments: vec![seg(0.0, 0.0, 0.0, 10.0, 0, "A")],
            ..RoutingResult::default()
        };
        let before = r.clone();
        for opts in [
            IoFanoutOptions {
                pad_diameter_mm: 0.0,
                ..tht_opts(1.0)
            },
            IoFanoutOptions {
                pad_diameter_mm: -1.0,
                ..tht_opts(1.0)
            },
            IoFanoutOptions {
                pad_diameter_mm: f64::NAN,
                ..tht_opts(1.0)
            },
            IoFanoutOptions {
                drill_mm: Some(0.0),
                ..tht_opts(1.0)
            },
            IoFanoutOptions {
                drill_mm: Some(f64::NAN),
                ..tht_opts(1.0)
            },
        ] {
            assert!(generate_io_fanout(&mut r, &ctx(40.0, 10.0, 2), &opts).is_err());
        }
        assert_eq!(r, before, "a rejected options set must not touch the result");
    }

    #[test]
    fn empty_result_needs_no_io() {
        let mut r = RoutingResult::default();
        assert!(generate_io_fanout(&mut r, &ctx(40.0, 10.0, 2), &tht_opts(0.4)).is_ok());
        assert!(r.io_pads.is_empty() && r.io_traces.is_empty());
    }

    #[test]
    fn every_terminal_gets_a_pad_on_its_nearest_edge() {
        // Two coils: layer-0 phase A spanning the full width (terminals on
        // both edges), layer-1 phase B in the lower half (both terminals on
        // the min edge).
        let mut r = RoutingResult {
            segments: vec![
                seg(5.0, 0.0, 5.0, 10.0, 0, "A"),
                seg(8.0, 2.0, 12.0, 2.0, 1, "B"),
            ],
            ..RoutingResult::default()
        };
        let c = ctx(40.0, 10.0, 2);
        generate_io_fanout(&mut r, &c, &tht_opts(0.4)).expect("generation succeeds");

        // 2 groups × 2 terminals = 4 pads / 4 traces.
        assert_eq!(r.io_pads.len(), 4);
        assert_eq!(r.io_traces.len(), 4);

        // Row min (y ≤ 5): A-start (5,0), B-start (8,2), B-end (12,2) —
        // x-ordered pads at margin=0.4 and step=(40−0.8)/2.
        let (d, l) = (0.4_f64, 40.0_f64);
        let expected_min_x = [d, d + (l - 2.0 * d) / 2.0, l - d];
        let min_y = d / 2.0;
        for (k, pad) in r.io_pads.iter().take(3).enumerate() {
            assert!((pad.position.x - expected_min_x[k]).abs() < 1e-12);
            assert!((pad.position.y - min_y).abs() < 1e-12);
        }
        // Row max: A-end (5,10) alone → centred.
        let max_pad = &r.io_pads[3];
        assert!((max_pad.position.x - l / 2.0).abs() < 1e-12);
        assert!((max_pad.position.y - (10.0 - d / 2.0)).abs() < 1e-12);

        // Nets and layers carry through from the coil terminals.
        let nets: Vec<&str> = r.io_pads.iter().map(|p| p.net.as_str()).collect();
        assert_eq!(nets, vec!["A", "B", "B", "A"]);
        let trace_layers: Vec<u32> = r.io_traces.iter().map(|t| t.layer).collect();
        assert_eq!(trace_layers, vec![0, 1, 1, 0]);
        // Pads numbered 1..N in emission order.
        for (i, pad) in r.io_pads.iter().enumerate() {
            assert_eq!(pad.number.as_deref(), Some((i + 1).to_string()).as_deref());
        }
    }

    #[test]
    fn tht_pads_span_all_layers_and_carry_the_drill() {
        let mut r = RoutingResult {
            segments: vec![seg(0.0, 0.0, 0.0, 10.0, 1, "A")],
            ..RoutingResult::default()
        };
        let c = ctx(40.0, 10.0, 4);
        generate_io_fanout(&mut r, &c, &tht_opts(0.5)).expect("generation succeeds");
        for pad in &r.io_pads {
            assert_eq!(pad.kind, IoPadKind::Tht);
            assert_eq!(pad.drill_mm, Some(0.2));
            assert_eq!(pad.layers, vec![0, 1, 2, 3], "THT pads span the stack");
            assert_eq!(pad.size, PadSize { x: 0.5, y: 0.5 });
        }
        for trace in &r.io_traces {
            assert_eq!(trace.role, IoTraceRole::Fanout);
            assert_eq!(trace.net, "A");
        }
    }

    #[test]
    fn board_edge_pads_sit_on_the_outline_of_their_fanout_layer() {
        // A horizontal coil near the min edge: both terminals are nearest the
        // y = 0 edge, so both castellated pads centre on that outline.
        let mut r = RoutingResult {
            segments: vec![seg(0.0, 1.0, 30.0, 1.0, 0, "C")],
            ..RoutingResult::default()
        };
        let c = ctx(40.0, 10.0, 2);
        generate_io_fanout(&mut r, &c, &IoFanoutOptions::board_edge(0.6))
            .expect("generation succeeds");
        assert_eq!(r.io_pads.len(), 2);
        for pad in &r.io_pads {
            assert_eq!(pad.kind, IoPadKind::BoardEdge);
            assert_eq!(pad.drill_mm, None, "surface pads have no drill");
            assert_eq!(pad.layers, vec![0], "surface pads sit on the fanout layer");
            assert!((pad.position.y - 0.0).abs() < 1e-12);
        }
    }

    #[test]
    fn placement_is_deterministic() {
        let build = || {
            let mut r = RoutingResult {
                segments: vec![
                    seg(5.0, 0.0, 5.0, 10.0, 0, "A"),
                    seg(8.0, 2.0, 12.0, 2.0, 1, "B"),
                    seg(15.0, 9.0, 15.0, 1.0, 1, "C"),
                ],
                ..RoutingResult::default()
            };
            generate_io_fanout(&mut r, &ctx(40.0, 10.0, 2), &tht_opts(0.4)).expect("ok");
            r
        };
        assert_eq!(build(), build(), "same inputs must give byte-identical IO");
    }

    #[test]
    fn single_edge_options_collapse_to_one_row() {
        let mut r = RoutingResult {
            segments: vec![seg(5.0, 0.0, 5.0, 10.0, 0, "A")],
            ..RoutingResult::default()
        };
        let c = ctx(40.0, 10.0, 2);
        let opts = IoFanoutOptions {
            edge: IoFanoutEdge::AcrossMin,
            ..tht_opts(0.4)
        };
        generate_io_fanout(&mut r, &c, &opts).expect("generation succeeds");
        assert!(r.io_pads.iter().all(|p| (p.position.y - 0.2).abs() < 1e-12));

        let opts = IoFanoutOptions {
            edge: IoFanoutEdge::AcrossMax,
            ..tht_opts(0.4)
        };
        let mut r = RoutingResult {
            segments: vec![seg(5.0, 0.0, 5.0, 10.0, 0, "A")],
            ..RoutingResult::default()
        };
        generate_io_fanout(&mut r, &c, &opts).expect("generation succeeds");
        assert!(r.io_pads.iter().all(|p| (p.position.y - 9.8).abs() < 1e-12));
    }

    #[test]
    fn terminal_on_a_pad_slot_still_gets_a_non_degenerate_fanout() {
        // A coil whose two terminals sit exactly on the two pad slots of the
        // min row (THT pads sit inset at y = d/2): both fanouts must be
        // nudged deterministically and remain strictly non-degenerate.
        let d = 0.4_f64;
        let l = 40.0_f64;
        let mut r = RoutingResult {
            segments: vec![seg(d, d / 2.0, l - d, d / 2.0, 0, "A")],
            ..RoutingResult::default()
        };
        let c = ctx(l, 10.0, 2);
        generate_io_fanout(&mut r, &c, &tht_opts(d)).expect("generation succeeds");

        assert_eq!(r.io_traces.len(), 2);
        for t in &r.io_traces {
            let len = ((t.end.x - t.start.x).powi(2) + (t.end.y - t.start.y).powi(2)).sqrt();
            assert!(len > 1e-6, "fanout length {len} must exceed the validator epsilon");
        }
        // The nudged pads stayed in bounds and moved deterministically by one
        // pad diameter away from the nearer board end.
        assert!((r.io_pads[0].position.x - (d + d)).abs() < 1e-12);
        assert!((r.io_pads[1].position.x - (l - 2.0 * d)).abs() < 1e-12);
        // The validator agrees (bounds + non-degenerate traces).
        crate::validator::Validator::validate(&r, &c, false).expect("generated IO must validate");
    }

    #[test]
    fn generated_io_passes_the_strict_validator() {
        let mut r = RoutingResult {
            segments: vec![
                seg(0.0, 0.0, 0.0, 10.0, 0, "A"),
                seg(0.0, 0.0, 0.0, 10.0, 1, "B"),
                seg(0.0, 0.0, 0.0, 10.0, 0, "C"),
            ],
            ..RoutingResult::default()
        };
        let c = ctx(40.0, 10.0, 2);
        generate_io_fanout(&mut r, &c, &tht_opts(0.4)).expect("generation succeeds");
        crate::validator::Validator::validate(&r, &c, false)
            .expect("in-bounds generated IO must pass the strict validator");
    }

    #[test]
    fn curves_only_groups_get_terminals_too() {
        let mut r = RoutingResult {
            curves: vec![crate::model::RouteCurve {
                start: Point::new(1.0, 2.0),
                mid: Point::new(2.0, 3.0),
                end: Point::new(3.0, 2.0),
                layer: 0,
                net: "A".into(),
                is_active: true,
            }],
            ..RoutingResult::default()
        };
        generate_io_fanout(&mut r, &ctx(40.0, 10.0, 2), &tht_opts(0.4)).expect("ok");
        assert_eq!(r.io_pads.len(), 2, "a curves-only group still has 2 terminals");
        assert_eq!(r.io_traces[0].start, Point::new(1.0, 2.0));
        assert_eq!(r.io_traces[1].start, Point::new(3.0, 2.0));
    }
}
